# Generated by Django 5.0.6 on 2024-06-07 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_producto', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)])),
                ('tipo', models.CharField(choices=[('SUCULENTAS', 'Suculentas'), ('MACETEROS', 'Maceteros'), ('FLORES', 'Flores'), ('SUSTRATOS', 'Sustratos'), ('OTRO', 'Otro'), ('TIERRA DE HOJA', 'Tierra de hoja')], max_length=25)),
                ('precio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(10000000)])),
                ('imagen', models.ImageField(null=True, upload_to='producto')),
            ],
        ),
    ]
