# Generated by Django 5.0.6 on 2024-07-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardineria_app', '0007_alter_producto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('SUCULENTAS', 'Suculentas'), ('SUSTRATOS', 'Sustratos'), ('TIERRA DE HOJA', 'Tierra de hoja'), ('OTRO', 'Otro'), ('FLORES', 'Flores'), ('MACETEROS', 'Maceteros')], max_length=25),
        ),
    ]
