# Generated by Django 5.0.6 on 2024-07-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardineria_app', '0008_persona_alter_producto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('OTRO', 'Otro'), ('FLORES', 'Flores'), ('SUCULENTAS', 'Suculentas'), ('TIERRA DE HOJA', 'Tierra de hoja'), ('MACETEROS', 'Maceteros'), ('SUSTRATOS', 'Sustratos')], max_length=25),
        ),
    ]
