<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-07-08 06:33
=======
# Generated by Django 5.0.6 on 2024-07-09 00:11
>>>>>>> r_jardineria

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardineria_app', '0008_alter_producto_tipo_alter_user_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
<<<<<<< HEAD
            field=models.CharField(choices=[('SUCULENTAS', 'Suculentas'), ('FLORES', 'Flores'), ('TIERRA DE HOJA', 'Tierra de hoja'), ('OTRO', 'Otro'), ('SUSTRATOS', 'Sustratos'), ('MACETEROS', 'Maceteros')], max_length=25),
=======
            field=models.CharField(choices=[('MACETEROS', 'Maceteros'), ('SUCULENTAS', 'Suculentas'), ('OTRO', 'Otro'), ('TIERRA DE HOJA', 'Tierra de hoja'), ('SUSTRATOS', 'Sustratos'), ('FLORES', 'Flores')], max_length=25),
>>>>>>> r_jardineria
        ),
    ]
