# Generated by Django 5.0.6 on 2024-07-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardineria_app', '0009_alter_producto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('MACETEROS', 'Maceteros'), ('OTRO', 'Otro'), ('TIERRA DE HOJA', 'Tierra de hoja'), ('FLORES', 'Flores'), ('SUSTRATOS', 'Sustratos'), ('SUCULENTAS', 'Suculentas')], max_length=25),
        ),
    ]
