# Generated by Django 5.0.6 on 2024-07-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardineria_app', '0009_alter_producto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('TIERRA DE HOJA', 'Tierra de hoja'), ('SUCULENTAS', 'Suculentas'), ('OTRO', 'Otro'), ('MACETEROS', 'Maceteros'), ('SUSTRATOS', 'Sustratos'), ('FLORES', 'Flores')], max_length=25),
        ),
    ]
